dist: trusty
sudo: required
language: erlang
otp_release:
  - 20.0
  - 19.0
  - 18.0
script:
  - cat /var/log/mongodb/mongod.log
  - make tests
addons:
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  - echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
  - sudo apt-get update -q
  - sudo rm -rf /var/lib/mongodb
  - sudo apt-get install -y mongodb-org
  - sudo service mongod start
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
